exclude:
  - node_modules
encoding: UTF-8
markdown: GMF
include:
  - assets
plugins:
  - jemoji
google_analytics: G-HFNEYKB0G4
nav:
  - text: Home
    icon: home
    permalink: /
  - text: Percorso Formativo
    icon: conversion_path
    permalink: /PercorsoFormativo/
  - text: Risorse
    icon: folder_open
    permalink: /Risorse/
  - text: Tirocinio
    icon: lab_research
    permalink: /Tirocinio/
  - text: Laurea
    icon: description
    permalink: /Laurea/
  - text: Gruppi
    icon: group
    permalink: /Comunicazione/
  - text: Orari
    icon: schedule
    permalink: /Orari/
